# Generated by Django 2.2.24 on 2022-05-17 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0001_articles_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Article',
        ),
    ]
