# Generated by Django 2.2.24 on 2022-05-18 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_favorites'),
    ]

    operations = [
        migrations.CreateModel(
            name='TomTest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iD', models.BigIntegerField()),
                ('name', models.CharField(max_length=256)),
                ('lastname', models.CharField(max_length=256)),
            ],
        ),
    ]
